name: alphanessone
description: "Official AlphanessOne App"
publish_to: 'none'

version: 1.49.03+94

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  google_sign_in: ^7.1.1
  cloud_firestore: ^6.0.0
  dynamic_color: ^1.7.0
  google_fonts: ^6.2.0
  logging: ^1.2.0
  hooks_riverpod: ^2.4.10
  flutter_hooks: ^0.21.2
  intl: ^0.20.1
  rxdart: ^0.28.0
  flutter_riverpod: ^2.4.10
  flutter_launcher_icons: ^0.14.1
  rename_app: ^1.3.2
  change_app_package_name: ^1.1.0
  flutter_local_notifications: ^19.2.0
  permission_handler: ^12.0.0+1
  go_router: ^16.0.0
  numberpicker: ^2.1.2
  fl_chart: ^1.0.0
  js: ^0.7.1
  material_color_utilities: ^0.11.1
  meta: ^1.11.0
  vm_service:
  flutter_slidable: ^4.0.0
  random_string: ^2.3.1
  google_sign_in_web: ^1.0.0
  firebase_storage: ^13.0.0
  image_picker: ^1.0.8
  path: ^1.9.0
  path_provider: ^2.1.3
  file_picker: ^8.0.6
  share_plus: ^9.0.0
  firebase_remote_config: ^6.0.0
  package_info_plus: ^8.0.0
  flutter_typeahead: ^5.2.0
  font_awesome_flutter: ^10.7.0
  in_app_update: ^4.2.2
  openfoodfacts: ^3.10.0
  multi_select_flutter: ^4.1.3
  in_app_purchase: ^3.2.1
  in_app_purchase_android: ^0.4.0+2
  url_launcher: ^6.3.0
  riverpod: ^2.5.1
  cloud_functions: ^6.0.0
  collection: ^1.18.0
  flutter_svg: ^2.0.10+1
  in_app_purchase_storekit: ^0.4.0
  uuid: ^4.4.2
  flutter_native_splash: ^2.4.1
  flutter_stripe: ^11.5.0
  flutter_staggered_grid_view: ^0.7.0
  # flutter_stripe_web: ^6.5.0  # Temporaneamente commentato per compatibilità con Flutter 3.32
  shared_preferences: ^2.2.2
  http: ^1.2.2
  envied: ^1.0.0
  build_runner: ^2.4.13
  flutter_markdown: ^0.7.4+3
  logger: ^2.0.2+1
  flutter_gemini: ^3.0.0
  lottie: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  envied_generator: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/animations/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  min_sdk_android: 21
  android_play_store_icon: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon.png
  branding_mode: bottom
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
