name: alphanessone
description: "Official AlphanessOne App"
publish_to: 'none'

version: 1.30.00+58

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.0
  dynamic_color: ^1.7.0
  google_fonts: ^6.2.0
  hooks_riverpod: ^2.4.10
  flutter_hooks: ^0.20.5
  intl: ^0.19.0
  rxdart: ^0.28.0
  flutter_riverpod: ^2.4.10
  flutter_launcher_icons: ^0.13.1
  rename_app: ^1.3.2
  change_app_package_name: ^1.1.0
  flutter_local_notifications: ^17.0.0
  permission_handler: ^11.3.0
  go_router: ^14.1.4
  numberpicker: ^2.1.2
  fl_chart: ^0.69.0
  js: ^0.7.1
  material_color_utilities: ^0.11.1
  meta: ^1.11.0
  vm_service:
  flutter_slidable: ^3.1.0
  random_string: ^2.3.1
  google_sign_in_web: ^0.12.4
  firebase_storage: ^12.0.0
  image_picker: ^1.0.8
  path: ^1.9.0
  path_provider: ^2.1.3
  firebase_remote_config: ^5.0.0
  package_info_plus: ^8.0.0
  flutter_typeahead: ^5.2.0
  font_awesome_flutter: ^10.7.0
  in_app_update: ^4.2.2
  openfoodfacts: ^3.10.0
  multi_select_flutter: ^4.1.3
  in_app_purchase: ^3.2.0
  in_app_purchase_android: ^0.3.6
  url_launcher: ^6.3.0
  riverpod: ^2.5.1
  cloud_functions: ^5.0.3
  collection: ^1.18.0
  flutter_svg: ^2.0.10+1
  in_app_purchase_storekit: ^0.3.17+2
  uuid: ^4.4.2
  flutter_native_splash: ^2.4.1
  flutter_stripe: ^11.1.0
  flutter_stripe_web: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/training_background.svg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    background_color: null
    theme_color: "#hexcode"
  windows:
    generate: true
    icon_size: 48
  macos:
    generate: true

flutter_native_splash:
  color: "#000000" # Colore di sfondo, simile al design del background
  background_image: assets/splash/background.png # Percorso dell'immagine del background
  image: assets/splash/icon.png # Percorso dell'icona trasparente
  android: true
  ios: true
  web: true
  android_gravity: center # Posiziona l'icona al centro su Android
  ios_content_mode: center # Posiziona l'icona al centro su iOS



