// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj0qSymOs5m0D829WcYe28Ok6Vlj9Boro',
    appId: '1:179277367624:web:e6afe062d8a02e0330cb7d',
    messagingSenderId: '179277367624',
    projectId: 'alphaness-322423',
    authDomain: 'alphaness-322423.firebaseapp.com',
    storageBucket: 'alphaness-322423.appspot.com',
    measurementId: 'G-TDJY4DKBEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASzxyOrOUus8G3DL2oLE-N5FG56RY-dhk',
    appId: '1:179277367624:android:f8d54e86b7dac30430cb7d',
    messagingSenderId: '179277367624',
    projectId: 'alphaness-322423',
    storageBucket: 'alphaness-322423.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Tldsz6RX3g18Wqty8lXATf-VWmPl4RU',
    appId: '1:179277367624:ios:79a107e6526e0c1b30cb7d',
    messagingSenderId: '179277367624',
    projectId: 'alphaness-322423',
    storageBucket: 'alphaness-322423.appspot.com',
    iosClientId: '179277367624-c8rp756q5jgi7t6oso5lng8l6he2591h.apps.googleusercontent.com',
    iosBundleId: 'com.example.alphanessone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7Tldsz6RX3g18Wqty8lXATf-VWmPl4RU',
    appId: '1:179277367624:ios:2614b150aa34d6a830cb7d',
    messagingSenderId: '179277367624',
    projectId: 'alphaness-322423',
    storageBucket: 'alphaness-322423.appspot.com',
    iosClientId: '179277367624-puf2tc4m6atim9395vna4pb4cngq0tgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.alphanessone.RunnerTests',
  );
}
