name: Build iOS IPA
on:
  push:
    branches:
      - main_future
  pull_request:
    branches:
      - main_future
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'

    - name: Cache CocoaPods
      uses: actions/cache@v2
      with:
        path: ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Install dependencies
      run: flutter pub get

    - name: Install CocoaPods
      run: sudo gem install cocoapods

    - name: Create Podfile
      run: |
        cd ios
        cat <<EOF > Podfile
        platform :ios, '16.0'
        target 'Runner' do
          use_frameworks!
          use_modular_headers!
          require File.expand_path('../.flutter-plugins', __FILE__)
        end
        post_install do |installer|
          installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
              config.build_settings['ENABLE_BITCODE'] = 'NO'
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
            end
          end
        end
        EOF

    - name: Install CocoaPods dependencies
      run: |
        cd ios
        pod repo update
        pod install

    - name: Build iOS
      run: flutter build ios --release --no-codesign

    - name: Create IPA
      run: |
        mkdir -p build/ios/ipa
        xcodebuild -workspace ios/Runner.xcworkspace \
          -scheme Runner \
          -sdk iphoneos \
          -configuration Release \
          -archivePath build/ios/archive/MyApp.xcarchive \
          archive
        xcodebuild -exportArchive \
          -archivePath build/ios/archive/MyApp.xcarchive \
          -exportPath build/ios/ipa \
          -exportOptionsPlist <(echo '{ "method": "development", "signingStyle": "manual", "teamID": "", "compileBitcode": false, "destination": "export" }') \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

    - name: Upload IPA
      uses: actions/upload-artifact@v2
      with:
        name: myapp-ipa
        path: build/ios/ipa/*.ipa
