name: Build Android AppBundle & iOS IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. Effettua il checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Installa Flutter (ultima versione stabile o specifica)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5' # Sostituisci con la versione desiderata

      # 3. Installa le dipendenze di Flutter
      - name: Install dependencies
        run: flutter pub get

      # 4. Build Android App Bundle (file .aab)
      - name: Build Android App Bundle
        run: flutter build appbundle --release

      # 5. Carica l'App Bundle (.aab) come artifact
      - name: Upload Android AAB
        uses: actions/upload-artifact@v3
        with:
          name: myapp-aab
          path: build/app/outputs/bundle/release/*.aab

      # 6. Build iOS IPA senza code signing
      - name: Build iOS IPA
        run: flutter build ipa --release --no-codesign

      # 7. Carica l'IPA come artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: myapp-ipa
          path: build/ios/ipa/*.ipa
